remote_theme: sighingnow/jekyll-gitbook/fork

toc:
    enabled: true
    h_min: 1
    h_max: 3

syntax_highlighter_style: colorful

collections:
  pages:
    output: true
    permalink: /:collection/:path/
